INSERT INTO CUSTOMER(ID, NAME, PHONE_NUMBER) VALUES (SEQ_CUST_ID.NEXTVAL, 'Rob', '1234567889')
INSERT INTO CUSTOMER(ID, NAME, PHONE_NUMBER) VALUES (SEQ_CUST_ID.NEXTVAL, 'Aditya', '1234567089')

INSERT INTO COFFEE_VARIETY(ID, NAME, DESCRIPTION, AVAILABLE_QUANTITY) VALUES (SEQ_COFFEE_VARIETY_ID.NEXTVAL, 'Instant', 'Instant', 50)
INSERT INTO COFFEE_VARIETY(ID, NAME, DESCRIPTION, AVAILABLE_QUANTITY) VALUES (SEQ_COFFEE_VARIETY_ID.NEXTVAL, 'Filtered', 'Filtered', 150)

