INSERT INTO CUSTOMER(ID, NAME, PHONE_NUMBER) VALUES (SEQ_CUST_ID.NEXTVAL, 'Rob', '1234567888')
INSERT INTO CUSTOMER(ID, NAME, PHONE_NUMBER) VALUES (SEQ_CUST_ID.NEXTVAL, 'Aditya', '1234567080')

INSERT INTO COFFEE_VARIETY(ID, NAME, DESCRIPTION, AVAILABLE_QUANTITY, PRICE) VALUES (SEQ_COFFEE_VARIETY_ID.NEXTVAL, 'Mocha', 'Instant', 50, 4.50)
INSERT INTO COFFEE_VARIETY(ID, NAME, DESCRIPTION, AVAILABLE_QUANTITY, PRICE) VALUES (SEQ_COFFEE_VARIETY_ID.NEXTVAL, 'Chaii', 'Filtered', 150, 2.75)

INSERT INTO ORDERS(ID, CUSTOMER_ID, COFFEE_VARIETY_ID, QUANTITY, ORDER_TIME) VALUES (SEQ_ORDERS_ID.NEXTVAL, 1, 2, 2, SYSDATE)
INSERT INTO ORDERS(ID, CUSTOMER_ID, COFFEE_VARIETY_ID, QUANTITY, ORDER_TIME) VALUES (SEQ_ORDERS_ID.NEXTVAL, 2, 2, 1, SYSDATE)