CREATE TABLE IF NOT EXISTS CUSTOMER
(
   ID INTEGER NOT NULL,
   NAME VARCHAR(255) NOT NULL,
   PHONE_NUMBER VARCHAR(255) NOT NULL UNIQUE,
   PRIMARY KEY(ID)
);

CREATE SEQUENCE IF NOT EXISTS SEQ_CUST_ID START WITH 1;

CREATE TABLE IF NOT EXISTS COFFEE_VARIETY
(
   ID INTEGER NOT NULL,
   NAME VARCHAR(255) NOT NULL,
   DESCRIPTION VARCHAR (255),
   AVAILABLE_QUANTITY INTEGER,
   PRIMARY KEY(ID)
);

CREATE SEQUENCE IF NOT EXISTS SEQ_COFFEE_VARIETY_ID START WITH 1;

CREATE TABLE IF NOT EXISTS ORDERS
(
   ID INTEGER NOT NULL,
   CUSTOMER_ID INT ,
   COFFEE_VARIETY_ID INT,
   ORDER_TIME TIMESTAMP,
   PRIMARY KEY(ID)
);

CREATE SEQUENCE IF NOT EXISTS SEQ_ORDERS START WITH 1;

ALTER TABLE ORDERS ADD FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID);

ALTER TABLE ORDERS ADD FOREIGN KEY (COFFEE_VARIETY_ID) REFERENCES COFFEE_VARIETY(ID);

