CREATE TABLE IF NOT EXISTS CUSTOMER
(
   ID INTEGER NOT NULL,
   NAME VARCHAR(255) NOT NULL,
   PHONE_NUMBER VARCHAR(255) NOT NULL,
   PRIMARY KEY(ID)
);

CREATE SEQUENCE IF NOT EXISTS SEQ_CUST_ID START WITH 1;

CREATE TABLE IF NOT EXISTS COFFEE_VARIETY
(
   ID INTEGER NOT NULL,
   COFFEE_NAME VARCHAR(255) NOT NULL,
   DESCRIPTION VARCHAR (255),
   PRIMARY KEY(ID)
);

CREATE SEQUENCE IF NOT EXISTS SEQ_COFFEE_VARIETY_ID START WITH 1;

CREATE TABLE IF NOT EXISTS ORDERS
(
   ID INTEGER NOT NULL,
   CUSTOMER_ID INT ,
   COFFEE_VARIETY_ID INT,
   ORDER_TIME TIMESTAMP,
   PRIMARY KEY(ID)
);

CREATE SEQUENCE IF NOT EXISTS SEQ_ORDERS START WITH 1;

-- ALTER TABLE ORDERS ADD FOREIGN KEY (CUSTOMER_ID) CUSTOMER(ID);
--
-- ALTER TABLE ORDERS ADD FOREIGN KEY (COFFEE_VARIETY_ID) COFFEE_VARIETY(ID);

